server:
  port: 9001

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: oauth2-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.253.199:8848
    sentinel:
      transport:
        dashboard: 192.168.253.199:8080
    stream:
      rocketmq:
        binder:
          name-server: 192.168.253.199:9876
      bindings:
        output:
          destination: test-topic
          content-type: application/json

  redis:
    host: 192.168.253.199
    port: 6379
    password: Wenqu@9527
    database: 0

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://192.168.253.199:3306/oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Wenqu@9527
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

dubbo:
  scan:
    base-packages: com.wenqu.controller, com.wenqu.service.impl
  application:
    name: oauth2-server-dubbo
  registry:
    address: nacos://192.168.253.199:8848
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  provider:
    loadbalance: roundrobin

mybatis:
  type-aliases-package: com.wenqu.domain
  mapper-locations: classpath:mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"

